name: CI

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [12.x, 14.x, 15.x, 16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          install-command: yarn --frozen-lockfile --silent

      - name: Check Prettier
        run: yarn prettier

      - name: Check Lint
        run: yarn lint

      - name: Check Tests
        run: yarn test

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          parallel: true
          flag-name: run-${{ matrix.node }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  coverage:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          parallel-finished: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [12.x, 14.x, 15.x, 16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          install-command: yarn --frozen-lockfile --silent

      - name: Build
        run: yarn build

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          install-command: yarn --frozen-lockfile --silent

      - name: Release
        run: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
